# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'songshare' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for songshare
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTLinkingIOS',
  ]
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  target 'songshare-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'songshareTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
